#pragma once
#include "PCNLayer.h"
#include <vector>

/**
 * @file PCNNetwork.h
 * @brief Defines the network implementation of a PC model.
 * 
 * This header includes implementations of model saving/loading, training/prediction, debugging, and layer appending.
 * 
 * Usage:
 *  #include <PCNNetwork.h>
 *  using namespace Deep;
 * 
 * Example:
 *  PCNetwork network();
 *  layer.AddLayer(&layer);
 * 
 * @note To run a network, please use `Compile()` to merge all layer arrays together in memory.
 * @version 1.0
 * @date 2026-06-21
 * @author Jack Rose
 */

namespace Deep
{
    /// @brief A predictive coding network is a bidirectional neural network with local neurons. Use `Compile()` to merge all layers. Then use `InferenceStep()` to predict outputs or `GenerationStep()` to generate inputs!
    class PCNetwork
    {
    public:
        PCNetwork() = default;
        ~PCNetwork();

        /// @brief Adds a layer to the network.
        /// @param inSize Layer input size
        /// @param outSize Layer output size
        /// @param lr Learning rate for layer
        /// @param ir Inference rate for layer
        /// @param stepSize Stepsize (# cycles per input)
        /// @param act Activation function
        void AddLayer(size_t inSize, size_t outSize, float lr = 1e-6, float ir = 1e-6, int stepSize = 30, ActivationFn act = relu) noexcept {
            layers.emplace_back(inSize, outSize, lr, ir, stepSize, act);
        }

        /// @brief Adds a layer to the network.
        /// @param layer Layer to move
        void AddLayer(PCLayer &&layer) {
            layers.push_back(std::move(layer));
        }

        /// @brief Allocates the layers' memory contiguously for increased cache locality. Not doing this will result in poor performance.
        /// @note It is always recommended you call this before running training.
        void Compile() noexcept;

        /// @brief Runs x on the bottom layer, such that the top layer \em infers an output.
        /// @param x Bottom-level "input" array
        void InferenceStep(float *x);

        /// @brief Runs the target on the top layer, such that the bottom layer \em generates an input.
        /// @param target Top-level "output" array
        void GenerationStep(float *target);

        /// @brief Runs the last few iterations of a bottom-up inference cycle not caught in the batch size.
        void FlushInference();

        /// @brief Runs the last few iterations of a top-down generative cycle not caught in the batch size.
        void FlushGeneration();

        /// @brief Returns the energy generated by an inference cycle
        /// @return Energy
        /// @warning Not tested completely yet! Do not rely on this currently.
        float GetTotalEnergy() const noexcept;

        /// @brief Saves the model's array `arr` to the path.
        /// @param path File path
        void SaveModel(const char *path) const noexcept;
        /// @brief Loads the model's array `arr` from the path.
        /// @param path File path
        void LoadModel(const char *path) noexcept;

        #ifdef _DEBUG
        /// @brief Prints out layer count, arena size, energy, and per-layer statistics.
        void DebugStats();
        #endif

    private:
    // @internal Size of total array, number of layers to compile, layers saved, and the master arena.
        size_t arenaSize;
        size_t pendingInferenceCount = 0;
        size_t pendingGenerationCount = 0;
        std::vector<PCLayer> layers;
        float *masterArena;
    };
}